### PR TITLE
Final version DB

### PR DESCRIPTION
**Pull request by Hamarko**
CREATE TABLE `description` (
`description_id` INT NOT NULL,
`ac_ref` text NOT NULL,
`paper_title` text,
`journal` text,
`replicants_name` text,
`pub_date` text,
`keywords` text,
`description` text,
`author1` text,
`author2` TEXT,
`author3` TEXT,
PRIMARY KEY(description_id)
);

CREATE TABLE `models` (
`model_id` INTEGER UNIQUE,
`internal_name` text NOT NULL UNIQUE,
`path` text NOT NULL,
`description_id` integer,
`interest` INTEGER,
`inflation` INTEGER,
`outputgap` INTEGER,
`outpu` INTEGER,
`interest_` INTEGER,
`fiscal_` INTEGER,
`taylor_rule` INTEGER,
`gr_rule` INTEGER,
PRIMARY KEY(model_id),
FOREIGN KEY(`description_id`) REFERENCES `description`(`description_id`)
);

CREATE TABLE `prules` (
`prule_id` INT UNIQUE,
`internal_name` text,
`description_id` int,
`param1` real,
`param5` real,
`param6` real,
`param7` real,
`param8` real,
`param14` real,
`param32` real,
`param33` real,
PRIMARY KEY(prule_id)
);

### CODE REVIEW

**Comment by gboehl** [comment]
Could you please submit to the devel branch?

Thanks!

Gregor

On 20.10.17 13:54:44, Hamarko wrote:
> CREATE TABLE `description` (
> `description_id` INT NOT NULL,
> `ac_ref` text NOT NULL,
> `paper_title` text,
> `journal` text,
> `replicants_name` text,
> `pub_date` text,
> `keywords` text,
> `description` text,
> `author1` text,
> `author2` TEXT,
> `author3` TEXT,
> PRIMARY KEY(description_id)
> );
> 
> CREATE TABLE `models` (
> `model_id` INTEGER UNIQUE,
> `internal_name` text NOT NULL UNIQUE,
> `path` text NOT NULL,
> `description_id` integer,
> `interest` INTEGER,
> `inflation` INTEGER,
> `outputgap` INTEGER,
> `outpu` INTEGER,
> `interest_` INTEGER,
> `fiscal_` INTEGER,
> `taylor_rule` INTEGER,
> `gr_rule` INTEGER,
> PRIMARY KEY(model_id),
> FOREIGN KEY(`description_id`) REFERENCES `description`(`description_id`)
> );
> 
> CREATE TABLE `prules` (
> `prule_id` INT UNIQUE,
> `internal_name` text,
> `description_id` int,
> `param1` real,
> `param5` real,
> `param6` real,
> `param7` real,
> `param8` real,
> `param14` real,
> `param32` real,
> `param33` real,
> PRIMARY KEY(prule_id)
> );
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/IMFS-MMB/mmci-cli/pull/5
> 
> -- Commit Summary --
> 
>   * Final version DB
> 
> -- File Changes --
> 
>     M mmb_input.db (0)
> 
> -- Patch Links --
> 
> https://github.com/IMFS-MMB/mmci-cli/pull/5.patch
> https://github.com/IMFS-MMB/mmci-cli/pull/5.diff
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/IMFS-MMB/mmci-cli/pull/5

-- 
Gregor Boehl
Postdoctoral Researcher
Institute for Monetary and Financial Stability
Goethe University Frankfurt
Mail: 	boehl@econ.uni-frankfurt.de
Web: 	https://gregorboehl.com

**Comment by Hamarko** [comment]
I've updated devel branch from main Repositories. But i don't add DB in this brach.
Do you want then i add DB in develop branch?

**Comment by gboehl** [comment]
Yes, of course. And please ONLY add the DB.


On 20.10.17 18:21:06, Hamarko wrote:
> I've updated devel branch from main Repositories. But i don't add DB in this brach.
> Do you want then i add DB in develop branch?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/IMFS-MMB/mmci-cli/pull/5#issuecomment-338285082

-- 
Gregor Boehl
Postdoctoral Researcher
Institute for Monetary and Financial Stability
Goethe University Frankfurt
Mail: 	boehl@econ.uni-frankfurt.de
Web: 	https://gregorboehl.com

**Comment by Hamarko** [comment]
I've close this pull request.
I've created two new pull requests. 
First pull request is adding DB in develop branch. https://github.com/IMFS-MMB/mmci-cli/pull/6
Second pull request is adding DB in master branch. https://github.com/IMFS-MMB/mmci-cli/pull/7

**Pull request closed without merging**
